CXX = g++-11 # Set your compiler here
CXXFLAGS = -std=c++20

clean:
	rm -f ./dynamic_and_static_dispatch

build:
	$(CXX) $(CXXFLAGS) dynamic_and_static_dispatch.cpp -o dynamic_and_static_dispatch
	
run:
	./dynamic_and_static_dispatch
