# Sorry rustaceans, cargo doesn't needed ;-) this is a too simple program.

clean:
	rm -f ./dynamic_and_static_dispatch

build:
	rustc dynamic_and_static_dispatch.rs
	
run:
	./dynamic_and_static_dispatch
